version: "3.8"
services:
  windows:
    container_name: windows
    build:
      context: .
      dockerfile: Dockerfile.win
    environment:
      VERSION: "xp"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - ./DATA:/storage
    restart: always
    stop_grace_period: 2m
    networks:
      - hack_network

  kali:
    container_name: kali
    build:
      context: .
      dockerfile: Dockerfile.kali
    #devices:
    #  - /dev/net/tun
    #cap_add:
    #  - NET_ADMIN
    ports:
      - "4200:4200"
    restart: always
    networks:
      - hack_network

networks:
  hack_network:
    driver: bridge
